services:
  postgres:
    image: postgres:15.8-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: matcha
      POSTGRES_DB: matcha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local