services:
  postgres:
    image: postgres:15.8-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: matcha      # Nom d'utilisateur
      POSTGRES_PASSWORD: matcha  # Mot de passe
      POSTGRES_DB: matcha    # Nom de la base de données
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistante des données
    ports:
      - "5432:5432"  # Exposition du port PostgreSQL

volumes:
  postgres_data:
    driver: local